package Vista;

import BaseDeDatos.ConexionBD;
import AccionesTablas.AccionesTablaClientes;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class JFDatosTablaClientes extends javax.swing.JFrame {

    ConexionBD con = new ConexionBD();
    String usuario = "root"; 
    String contrasena = "grupo4hlm"; 
    Connection cn = con.conexion(usuario, contrasena);  
    DefaultTableModel modelo;
    AccionesTablaClientes accionesTabla;
    private TableRowSorter trsfiltro,trsfiltro1, trsfiltro2 ;
    String filtro, filtro1, filtro2;

    public JFDatosTablaClientes() {
        initComponents();
        
        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);

        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo Cliente");
        modelo.addColumn("Nombre Cliente");
        modelo.addColumn("Télefono Cliente");
        modelo.addColumn("Cédula Cliente");
        jTablaClienteCompleto.setModel(modelo);
        accionesTabla = new AccionesTablaClientes(cn, modelo);
        accionesTabla.ocultarComponentes(jTBuscarCodigo, jTBuscarCedula, jTBuscarNombre, jLCedula, jLCodigo, jLNombre, panelEditar, jBActualizarDatos);
        accionesTabla.cargarDatos(); 
        
    }
    
    private void actualizarTabla() {
        accionesTabla.cargarDatos();
    }
    
    @Override
    public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Polituti.png"));
    return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFNCliente = new javax.swing.JTextField();
        JTFNTelefono = new javax.swing.JTextField();
        JTFNCedula = new javax.swing.JTextField();
        JBInsertar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBBuscarNombre = new javax.swing.JButton();
        jBBuscarcodigo = new javax.swing.JButton();
        jBBuscarCedula = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTBuscarNombre = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jTBuscarCodigo = new javax.swing.JTextField();
        jLCedula = new javax.swing.JLabel();
        jTBuscarCedula = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        panelEditar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFNombreEditar = new javax.swing.JTextField();
        jFTelefonoEditar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFCedulaEditar = new javax.swing.JTextField();
        jBActualizarDatos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaClienteCompleto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENTES");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingrese datos del Cliente"));

        jLabel1.setText("Nombre del Cliente");

        jLabel2.setText("Número de Telefono");

        jLabel3.setText("Número de Cédula");

        JTFNCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNClienteActionPerformed(evt);
            }
        });
        JTFNCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNClienteKeyTyped(evt);
            }
        });

        JTFNTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNTelefonoActionPerformed(evt);
            }
        });
        JTFNTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNTelefonoKeyTyped(evt);
            }
        });

        JTFNCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNCedulaActionPerformed(evt);
            }
        });
        JTFNCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNCedulaKeyTyped(evt);
            }
        });

        JBInsertar.setText("Insertar");
        JBInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(JTFNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JBInsertar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JTFNTelefono)
                            .addComponent(JTFNCedula))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFNTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFNCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(JBInsertar)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insertar", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingrese el Dato por el que quiera Buscar"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones de Busqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 12))); // NOI18N

        jBBuscarNombre.setText("Buscar por Nombre");
        jBBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarNombreActionPerformed(evt);
            }
        });

        jBBuscarcodigo.setText("Buscar por Codigo");
        jBBuscarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarcodigoActionPerformed(evt);
            }
        });

        jBBuscarCedula.setText("Buscar por Cédula");
        jBBuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBuscarNombre)
                    .addComponent(jBBuscarcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBuscarCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBBuscarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscarcodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBBuscarCedula)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLNombre.setText("Buscar por Nombre");

        jTBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBuscarNombreActionPerformed(evt);
            }
        });
        jTBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarNombreKeyTyped(evt);
            }
        });

        jLCodigo.setText("Buscar por Codigo");

        jTBuscarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarCodigoKeyTyped(evt);
            }
        });

        jLCedula.setText("Buscar por Cédula");

        jTBuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTBuscarCedulaKeyTyped(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        panelEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Modificar los Datos"));

        jLabel7.setText("Nombre del Cliente");

        jLabel8.setText("Teléfono del Cliente");

        jLabel9.setText("Cédula del Cliente");

        jFNombreEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFNombreEditarKeyTyped(evt);
            }
        });

        jFTelefonoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTelefonoEditarKeyTyped(evt);
            }
        });

        jFCedulaEditar.setEditable(false);
        jFCedulaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCedulaEditarActionPerformed(evt);
            }
        });
        jFCedulaEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFCedulaEditarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFCedulaEditarKeyTyped(evt);
            }
        });

        jBActualizarDatos.setText("Actualizar Datos");
        jBActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTelefonoEditar)
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(jFCedulaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jFNombreEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(227, 227, 227))
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jBActualizarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFTelefonoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jFCedulaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBActualizarDatos)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTBuscarNombre)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre)
                            .addComponent(jLCodigo)
                            .addComponent(jLCedula))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addComponent(jTBuscarCodigo)
                    .addComponent(jTBuscarCedula))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBModificar)
                .addGap(68, 68, 68))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar)
                    .addComponent(jBModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel3);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });

        jTablaClienteCompleto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Cliente", "Nombre Cliente", "Télefono Cliente", "Cédula Cliente"
            }
        ));
        jTablaClienteCompleto.setFocusable(false);
        jScrollPane1.setViewportView(jTablaClienteCompleto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBRegresar)
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegresar)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBInsertarActionPerformed
    String nombreCliente = JTFNCliente.getText().trim();
    String telefonocliente = JTFNTelefono.getText().trim();
    String cedulaCliente = JTFNCedula.getText().trim();
    
    if (nombreCliente.isEmpty() || telefonocliente.isEmpty() || cedulaCliente.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }
     
    accionesTabla.manejarInsercionCliente(JTFNCliente, JTFNTelefono, JTFNCedula);
    JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
     this.JTFNCedula.setText("");
     this.JTFNCliente.setText("");
     this.JTFNTelefono.setText("");
    actualizarTabla();
    }//GEN-LAST:event_JBInsertarActionPerformed

    private void jBBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarNombreActionPerformed
        this.jTBuscarCodigo.setVisible(false);
        this.jLCodigo.setVisible(false);
        this.jTBuscarCedula.setVisible(false);
        this.jTBuscarNombre.setVisible(true);
        this.jLCedula.setVisible(false);
        this.jLNombre.setVisible(true);
        this.panelEditar.setVisible(false);
        this.jBActualizarDatos.setVisible(false);

        jTBuscarNombre.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = jTBuscarNombre.getText();
                jTBuscarNombre.setText(cadena);
                repaint();
                filtro1();
            }
        });
    }//GEN-LAST:event_jBBuscarNombreActionPerformed

    private void jTBuscarNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarNombreKeyTyped
        trsfiltro1 = new TableRowSorter(jTablaClienteCompleto.getModel());
        jTablaClienteCompleto.setRowSorter(trsfiltro1);
        AccionesTablaClientes.validarSoloLetras(evt);

    }//GEN-LAST:event_jTBuscarNombreKeyTyped

    private void JTFNClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNClienteActionPerformed

    private void JTFNTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNTelefonoActionPerformed

    private void JTFNCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNCedulaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBBuscarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarcodigoActionPerformed
        this.jTBuscarCodigo.setVisible(true);
        this.jLCodigo.setVisible(true);
        this.jTBuscarCedula.setVisible(false);
        this.jTBuscarNombre.setVisible(false);
        this.jLCedula.setVisible(false);
        this.jLNombre.setVisible(false);
        jTBuscarCodigo.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = jTBuscarCodigo.getText();
                jTBuscarCodigo.setText(cadena);
                repaint();
                filtro();
            }
        });
    }//GEN-LAST:event_jBBuscarcodigoActionPerformed

    private void jTBuscarCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarCodigoKeyTyped
        trsfiltro = new TableRowSorter(jTablaClienteCompleto.getModel());
        jTablaClienteCompleto.setRowSorter(trsfiltro);
        AccionesTablaClientes.validarNumeros(evt);
    }//GEN-LAST:event_jTBuscarCodigoKeyTyped

    private void jBBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCedulaActionPerformed
        this.jTBuscarCodigo.setVisible(false);
        this.jLCodigo.setVisible(false);
        this.jTBuscarCedula.setVisible(true);
        this.jTBuscarNombre.setVisible(false);
        this.jLNombre.setVisible(false);
        this.jLCedula.setVisible(true);
        this.jBActualizarDatos.setVisible(true);
        jTBuscarCedula.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = jTBuscarCedula.getText();
                jTBuscarCedula.setText(cadena);
                repaint();
                filtro2();
            }
        });
     
    }//GEN-LAST:event_jBBuscarCedulaActionPerformed

    private void jTBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBuscarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarNombreActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
                                         
    int filaSeleccionada = jTablaClienteCompleto.getSelectedRow();

    if (filaSeleccionada >= 0) {
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el cliente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            accionesTabla.eliminarCliente(filaSeleccionada, jTablaClienteCompleto, modelo, cn);
            
            jTablaClienteCompleto.clearSelection();
            
            if (trsfiltro != null) trsfiltro.setRowFilter(null);
            if (trsfiltro1 != null) trsfiltro1.setRowFilter(null);
            if (trsfiltro2 != null) trsfiltro2.setRowFilter(null);
            
            jTBuscarNombre.setText("");
            jTBuscarCodigo.setText("");
            jTBuscarCedula.setText("");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione una fila para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
    this.panelEditar.setVisible(true);
    this.jBActualizarDatos.setVisible(true);
    accionesTabla.manejarModifiCliente(jTablaClienteCompleto, jFNombreEditar, jFTelefonoEditar, jFCedulaEditar, panelEditar);
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarDatosActionPerformed
      String nuevoNombre = jFNombreEditar.getText();
    String nuevoPrecio = jFCedulaEditar.getText();
    String nuevaCantidad = jFTelefonoEditar.getText();

    int filaSeleccionada = jTablaClienteCompleto.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
        // Llamar al método de actualización
        accionesTabla.manejarActualizacionCliente(filaSeleccionada, nuevoNombre, nuevoPrecio, nuevaCantidad, jTablaClienteCompleto, panelEditar);
        
        // Limpiar selección de la tabla
        jTablaClienteCompleto.clearSelection();

        // Limpiar filtros
        if (trsfiltro != null) trsfiltro.setRowFilter(null);
        if (trsfiltro1 != null) trsfiltro1.setRowFilter(null);
        if (trsfiltro2 != null) trsfiltro2.setRowFilter(null);

        // Limpiar campos de texto
        jTBuscarNombre.setText("");
        jTBuscarCodigo.setText("");
        jTBuscarCedula.setText("");

        // Ocultar panel de edición y botón de actualizar datos
        this.panelEditar.setVisible(false);
        this.jBActualizarDatos.setVisible(false);
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione una fila para actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_jBActualizarDatosActionPerformed

    private void jTBuscarCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarCedulaKeyTyped
        trsfiltro2 = new TableRowSorter(jTablaClienteCompleto.getModel());
        jTablaClienteCompleto.setRowSorter(trsfiltro2);
         // Asume que tienes una instancia de AccionesTablaClientes
    AccionesTablaClientes accionesTablaClientes = new AccionesTablaClientes(cn, modelo);

    AccionesTablaClientes.validarNumeros(evt); // Asume que este método es estático o lo llamas de alguna manera adecuada

    if (JTFNCedula.getText().length() >= 10) { 
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
    }

    if (JTFNCedula.getText().length() == 2) {
        String codigo = JTFNCedula.getText();
        if (!accionesTablaClientes.validarCodigoProvincia(codigo)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
    }//GEN-LAST:event_jTBuscarCedulaKeyTyped

    private void jFTelefonoEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTelefonoEditarKeyTyped
    AccionesTablaClientes.validarNumeros(evt);
    if(jFTelefonoEditar.getText().length()>= 10){ 
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jFTelefonoEditarKeyTyped

    private void jFCedulaEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFCedulaEditarKeyTyped
    
    AccionesTablaClientes accionesTablaClientes = new AccionesTablaClientes(cn, modelo);

    AccionesTablaClientes.validarNumeros(evt);

    if (JTFNCedula.getText().length() >= 10) { 
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
    }

    if (JTFNCedula.getText().length() == 2) {
        String codigo = JTFNCedula.getText();
        if (!accionesTablaClientes.validarCodigoProvincia(codigo)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
     
    }//GEN-LAST:event_jFCedulaEditarKeyTyped

    private void JTFNTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNTelefonoKeyTyped
    AccionesTablaClientes.validarNumeros(evt);
    if(JTFNTelefono.getText().length()>= 10){ 
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_JTFNTelefonoKeyTyped

    private void JTFNCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNCedulaKeyTyped
     // Asume que tienes una instancia de AccionesTablaClientes
    AccionesTablaClientes accionesTablaClientes = new AccionesTablaClientes(cn, modelo);

    AccionesTablaClientes.validarNumeros(evt); // Asume que este método es estático o lo llamas de alguna manera adecuada

    if (JTFNCedula.getText().length() >= 10) { 
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
    }

    if (JTFNCedula.getText().length() == 2) {
        String codigo = JTFNCedula.getText();
        if (!accionesTablaClientes.validarCodigoProvincia(codigo)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
    }//GEN-LAST:event_JTFNCedulaKeyTyped

    private void JTFNClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNClienteKeyTyped
    AccionesTablaClientes.validarSoloLetras(evt);
    }//GEN-LAST:event_JTFNClienteKeyTyped

    private void jFNombreEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFNombreEditarKeyTyped
    AccionesTablaClientes.validarSoloLetras(evt);

    }//GEN-LAST:event_jFNombreEditarKeyTyped

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        new JFMenuOpciones().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jFCedulaEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFCedulaEditarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFCedulaEditarKeyReleased

    private void jFCedulaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCedulaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFCedulaEditarActionPerformed
public void filtro2() {
    filtro2 = jTBuscarCedula.getText();
    // Agregar (?i) al inicio de la expresión regular para hacerla insensible al caso
    trsfiltro2.setRowFilter(RowFilter.regexFilter("(?i)" + filtro2, 3));
}

    public void filtro1(){
    filtro1 = jTBuscarNombre.getText();
     trsfiltro1.setRowFilter(RowFilter.regexFilter("(?i)" + filtro1, 1));
    }
public void filtro() {
    filtro = jTBuscarCodigo.getText();
    trsfiltro.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, 0));
}
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDatosTablaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBInsertar;
    private javax.swing.JTextField JTFNCedula;
    private javax.swing.JTextField JTFNCliente;
    private javax.swing.JTextField JTFNTelefono;
    private javax.swing.JButton jBActualizarDatos;
    private javax.swing.JButton jBBuscarCedula;
    private javax.swing.JButton jBBuscarNombre;
    private javax.swing.JButton jBBuscarcodigo;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jFCedulaEditar;
    private javax.swing.JTextField jFNombreEditar;
    private javax.swing.JTextField jFTelefonoEditar;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscarCedula;
    private javax.swing.JTextField jTBuscarCodigo;
    private javax.swing.JTextField jTBuscarNombre;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablaClienteCompleto;
    private javax.swing.JPanel panelEditar;
    // End of variables declaration//GEN-END:variables
}
